### ISSUE TITLE
What is the license of this awesome project?

### ISSUE THREAD

**Issue by leaf-node** [itkach/mwscrape2slob#7]
Cool project, thanks! : )

**Comment by bkuhls** [comment]
What about GPL3?
https://github.com/itkach/mwscrape2slob/blob/master/setup.py#L23

In addition parts of the project use the Apache-2.0 and the GPL license:
https://git.buildroot.net/buildroot/tree/package/python-mwscrape2slob/python-mwscrape2slob.mk#n9

**Comment by leaf-node** [comment]
Ah, thanks for pointing that out to me @bkuhls, I mised that. : ) It's good to see that that GPLv3 is being used for at lest some parts.

If all the code (including the packaged dependency) is covered by GPLv3 or Apache 2.0, it would be helpful to users to say that part of the program is covered by GPLv3 and other parts by Apache 2.0. That way users will know that the project free software.
